drop table user if exists;
create table user(
	id bigint generated by default as identity,
-- 	username varchar(40),
-- 	name varchar(20),
-- 	age int(3),
-- 	balance decimal(10,2),
  x1 int(3),
  y1 int(3),
  x2 int(3),
  y2 int(3),
  x3 int(3),
  y3 int(3),
  x4 int(3),
  y4 int(3),
  x5 int(3),
  y5 int(3),
	primary key(id),
);